### PR TITLE
Bash script to install extensions

### PR DESCRIPTION
**Pull request by nkorinek**
Bash script to run these lines

```
jupyter nbextension install --sys-prefix --py nbgrader --overwrite
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader
```

### CODE REVIEW

**Comment by lwasser** [comment]
woah @nkorinek you are a rockstar. Can you add instructions on how to call this file to the contributing.rst file in this same PR?!! 
i'm super impressed that you went ahead and did this. Thank you!

**Comment by nkorinek** [comment]
@lwasser added the info into the contributing file

**Comment by lwasser** [comment]
tested locally and it works like a charm!!  this addresses #81 merging!!

**Comment by lwasser** [comment]
thank you @nkorinek !!!

**Comment by lwasser** [comment]
closes #76

**Pull request merged**
