### PR TITLE
Create extra files from directory, not config

### PR DESCRIPTION
**Pull request by kcranston**
Rather than having the extra files (the ones that we want for each assignment) specified in the config, instead use an extra_files directory. This PR modifies the behaviour of abc-quickstart (it creates the extra_files directory, based on abcclassroom/example-data) as well as the two abc-template scripts. 

Addresses #195

### CODE REVIEW

**Comment by kcranston** [comment]
Note that this is going to require some changes to local existing courses - namely, creating an `extra_files` directory in the top-level course_dir.

**Comment by lwasser** [comment]
PUll down and test -- changes both quickstart and template scripts - extra files are being added from the dir rather than the config!

**Comment by lwasser** [comment]
i believe we can merge this. i will merge it and see how it goes!!

**Comment by lwasser** [comment]
closing this because it's in #261 which also updated the precommit to python 3.8 so i could build locally. will update everything to python 3.8 in a separate PR.

**Pull request closed without merging**
