### PR TITLE
Move ABC to New GitHub authentication

### PR DESCRIPTION
**Pull request by kcranston**
This re-implements the abc-init script so that it no longer uses the soon-to-be-deprecated username + password authentication to generate a personal access token. We now have a GitHub App (abc-classroom-bot) and authenticate using the app to generate an OAuth access token. I still need to write docs, but this can be tested by running `abc-init`.

Addresses #328 and #326 

Note that the existing github3 calls work with the new access token, so replacing those does not need to be done immediately. Should still be done, but there isn't the same level of urgency as getting the token generation replaced.

### CODE REVIEW

**Comment by kcranston** [comment]
I put my notes on a wiki page: https://github.com/earthlab/abc-classroom/wiki/GitHub-Authentication-Notes

**Comment by kcranston** [comment]
I still need to implement more / better error handling, so having some new eyes on this would be great. @lwasser and @nkorinek - can one or both of you test the new `abc-init` on this branch. 

* run `abc-init` without changing anything in your local setup
* move the ~/.abc-classroom.tokens.yml` file and re-run `abc-init` to force it to generate a new token 

You should see a message about successfully authenticating as your github username.

**Comment by nkorinek** [comment]
@kcranston hey! I tried it and it seemed to work for me. It gave me a code and had me activate my device on github.

**Comment by kcranston** [comment]
PR now includes docs. Ready to merge if everything looks ok!

**Comment by lwasser** [comment]
@kcranston it looks like some things are not building. can you run `make docs -B` locally to ensure the docs are building? CI is failing.  i will test this out some time this week!

**Pull request merged**
