### PR TITLE
helper function for copying files to template repos

### PR DESCRIPTION
**Pull request by kcranston**
Implements a helper function, `copy_files` in `utils.py` for copying files from one directory to another, excluding files that match patterns in a `files_to_ignore` list. Helper uses the python 3.8 [`copytree`]( https://docs.python.org/3.8/library/shutil.html#shutil.copytree), which allows the destination directory to already exists.

In `template.py`, the new `copy_files_to_template_repo` uses this helper to copy files from the release dir and the extra_files dir (if it exists). 

Note that the list of files_to_ignore can now use wildcards, e.g. *.csv to exclude patterns, in addition to full-text matching. 

Addresses the template portion of #382

### CODE REVIEW

**Comment by nkorinek** [comment]
Ok so slight issue with this pr. I added `*.json` in files to ignore and got an error when running `abc-new-template`. Screenshots of my config and the error below. 

image
image

**Comment by kcranston** [comment]
Good catch, @nkorinek ! That is indeed a yaml import issue. I'll take a look at ignoring aliases (`*`) when loading the config.

**Comment by kcranston** [comment]
The '*' is a special character in yaml, so we need to add quotes around wildcards in the config. Now, if you have an unquoted wildcard, you should see a friendly error message with a link to the configuration page on readthedocs. 

```
Error reading config.yml. This can happen if the config contains an unquoted *. Try adding quotes around any wildcards in 
the config, e.g. '*.csv'. See https://abc-classroom.readthedocs.io/en/latest/get-started/configuration.html 
for details.
```

I did investigate modifying the yaml parser to ignore aliases, but that was not straightforward, and I worried about abc-classroom allowing invalid yaml.

**Comment by lwasser** [comment]
ok great. what do you need here now @kcranston do you want us to test this pr?

**Comment by kcranston** [comment]
Yes, please test! Let me know if things aren't working as hoped / expected.

**Comment by nkorinek** [comment]
@kcranston hey! I have tested this, I got the error message you added when I formatted it incorrectly like I did on my first test, and when I formatted it correctly it seems too work perfectly!

**Pull request merged**
