### PR TITLE
Script for cloning student repos

### PR DESCRIPTION
**Pull request by kcranston**
Ready for testing!

### CODE REVIEW

**Comment by lwasser** [comment]
weird  this worked last week. i reinstalled and am starting from scratch

```
(abc-dev) CIRES-EL-LM-020:earth-analytics-test leahwasser$ abc-assignment-template ps1
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/abc-dev/bin/abc-assignment-template", line 11, in <module>
    load_entry_point('abc-classroom', 'console_scripts', 'abc-assignment-template')()
  File "/Users/leahwasser/miniconda3/envs/abc-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/leahwasser/miniconda3/envs/abc-dev/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2851, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'abc-assignment-template') not found
```

**Comment by kcranston** [comment]
That is the old script name. After merging PR #121,  `abc-assignment-template` is `new-template` and `update-template`. Is your local repo up-to-date?

**Comment by lwasser** [comment]
thank you @kcranston this is a docs issue i realized :) they are definitely out of date but i'm updating them as i go now. my apologies. i was calling the old code following the instructions :)

**Comment by lwasser** [comment]
more leah error:
i made a roster manually
```
"identifier","github_username","github_id","name"
"Leah Wasser","lwasser","7649194",""
```
then ran 
`abc-clone ps1`

and got
```
(abc-dev) CIRES-EL-LM-020:earth-analytics-test leahwasser$ abc-clone ps1
Loading configuration from config.yml
Missing repositories for these students:  ['lwasser']
```

[but that repo does exist](https://github.com/earth-analytics-edu/ea-ps1-lwasser). what did i do wrong?

**Comment by kcranston** [comment]
Should merge #141 before this one (and there will probably be merge conflicts to clean up).

**Comment by lwasser** [comment]
ok #141  has been merged and you are correct - merge conflicts here now!!

**Comment by kcranston** [comment]
I'll fix the merge conflicts and merge master. Will ping when ready.

**Comment by lwasser** [comment]
wonderful. thank you @kcranston !! the codacy tool is kind of interesting although some of the things it's flagging i need to learn a bit more about. i can remove it if it gets annoying.

**Comment by lwasser** [comment]
@kcranston sorr, please remind me again. merge this or wait? it just still says WIP! i'm happy to play with abc-classroom on master if it makes life easier now.

**Comment by lwasser** [comment]
OR i could play with it here in this pr. just let me know what you prefer :)

**Comment by kcranston** [comment]
Go ahead and merge so you can test on your local master. We can chat about some of missing test coverage (tests that involve external services) on our call today.

**Comment by lwasser** [comment]
ok awesome. thanks @kcranston !! merging!

**Pull request merged**
