### PR TITLE
add external file prefix to set_github_auth

### LINKED ISSUE #163: Running abc-init results in error (varying on abc-classroom install method)
If abc-classroom has been installed using ```pip install abc-classroom```, running ```abc-init``` results in a token NOT being generated on GitHub, and a generated error in CLI:
```
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-init", line 8, in <module>
    sys.exit(init())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 51, in init
    gh_auth = get_github_auth()
NameError: name 'get_github_auth' is not defined
```

If abc-classroom has been installed using ```pip install git+git://github.com/earthlab/abc-classroom```, running ```abc-init``` results in a token generated on GitHub, but a generated error in CLI:
```
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-init", line 8, in <module>
    sys.exit(init())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 93, in init
    set_github_auth({"token": auth.token, "id": auth.id})
NameError: name 'set_github_auth' is not defined
```

In either case, ```.abc-classroom.tokens.yml``` is not created under the home directory.

### PR DESCRIPTION
**Pull request by kcranston**
Fixes #163 (need to issue new release so that version of pip has same behaviour as local install)

### CODE REVIEW

**Comment by lwasser** [comment]
@kcranston i noticed that a few other calls in that module might be missing the `cf.` module alias. should we fix them all? alternatively we could add `from .config import get_ ...` at the top and just leave them . thoughts? 

this is in main see lines 166, 261, etc!! 
example here: https://github.com/earthlab/abc-classroom/blob/74df8e72bfa983181a89692d4645ccc296b8741f/abcclassroom/__main__.py#L166

**Comment by kcranston** [comment]
All of the other instances are in the old, unused methods. Since we can't test these manually, and there are no unit tests, I simply moved all of the old code to the bottom of the file and commented it out. Still there for reference, but no longer maintained.

**Comment by lwasser** [comment]
ok great. i wondered because it wasn't throwing any errors. that's perfect for now. thank you i'll merge this.

**Comment by lwasser** [comment]
@kcranston i'll update the change log when i bump but in the future can you get into the habit of updating the change log as you submit pr's ? thank you for this!!

**Comment by lwasser** [comment]
thank you @kcranston i'll ignore the point of failure. i can have codacy ignore our changelog.

**Pull request merged**
