### PR TITLE
Refactor template script

### PR DESCRIPTION
**Pull request by kcranston**
This is the refactoring of the new-assignment-template script into a 'new' and an 'update' script as per the discussion in #105 . Ready for initial testing - does it work how you expect? Should we change any of the default cmdline args? 

Summary of new scripts:

* `abc-new-template assignmentname`  - supports initial creation workflow; will create new directory, copy / create files, init + add + commit local repo, but will not push to github by default
* `abc-update-template assignmentname` - supports modification of existing dir and push to github; will add / modify files and push to github 

Run either script with the `-h` flag to see options and defaults. Note that the back-end implementation is the same, so you can get the `update` behaviour from the `new` script by using the `--mode merge` and `--github` options.

### CODE REVIEW

**Comment by lwasser** [comment]
MINOR: Ran:
```
$ abc-new-template # missing assignment name:
```
Got:
```
abc-new-template: error: the following arguments are required: assignment
```
probably want that to say assignment-name to be more specific for the user
When i then tried to update the assignment i got the error below:
```
(abc-dev) CIRES-EL-LM-020:my-course leahwasser$ abc-new-template assignment1
Loading configuration from config.yml
Directory /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template already exists; re-run with '--mode merge' or '--mode delete', or delete / move directory before re-running
(abc-dev) CIRES-EL-LM-020:my-course leahwasser$ abc-update-template assignment1
Loading configuration from config.yml
Template directory /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template already exists; will keep directory but overwrite existing files with same names
repo path: /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
Getting assignment files
copying /Users/leahwasser/Documents/github/0-python/test-class/my-course/nbgrader/release/assignment1/2019-09-03-python-fundamentals-landing-page.ipynb to /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
copying /Users/leahwasser/Documents/github/0-python/test-class/my-course/nbgrader/release/assignment1/2019-09-03-python-fundamentals-landing-page.md to /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
Copied 2 files
Creating 2 extra files
No changes to local repository.
Creating remote repo ea-assignment1-template
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/abc-dev/bin/abc-update-template", line 11, in <module>
    load_entry_point('abc-classroom', 'console_scripts', 'abc-update-template')()
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/__main__.py", line 474, in update_template
    template.new_update_template(args)
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/template.py", line 39, in new_update_template
    template_repo_path, organization, repo_name, token
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/template.py", line 51, in create_or_update_remote
    github.create_repo(organization, repo_name, token)
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/github.py", line 151, in create_repo
    organization = github_obj.organization(org)
  File "/Users/leahwasser/miniconda3/envs/abc-dev/lib/python3.7/site-packages/github3/github.py", line 1566, in organization
    json = self._json(self._get(url), 200)
  File "/Users/leahwasser/miniconda3/envs/abc-dev/lib/python3.7/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.ForbiddenError: 403 API rate limit exceeded for user ID 7649194.

```

**Comment by lwasser** [comment]
@kcranston can you please have a look at that error above? i can't seem to get update-template to work.

**Comment by kcranston** [comment]
That's a [rate limiting](https://developer.github.com/v3/#rate-limiting) error. Strange. If I run `curl -i https://api.github.com/users/lwasser `, I don't see you anywhere close to the limit.

**Comment by lwasser** [comment]
yes it's also weird @kcranston because i'm doing normal github stuff today but i haven't been pinging it or anything over and over!! just a few pushes, pulls and such. 

i'm not sure why this is happening.

**Comment by kcranston** [comment]
What do you get when you run `curl -u lwasser:PERSONAL_ACCESS_TOKEN https://api.github.com/rate_limit` (substituting the token you generated for abcclassroom, which exists in `~/.abc-classroom.tokens.yml`).

**Comment by lwasser** [comment]
ok...this almost worked
```
(abc-dev) CIRES-EL-LM-020:my-course leahwasser$ abc-update-template assignment1
Loading configuration from config.yml
Template directory /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template already exists; will keep directory but overwrite existing files with same names
repo path: /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
Getting assignment files
copying /Users/leahwasser/Documents/github/0-python/test-class/my-course/nbgrader/release/assignment1/2019-09-03-python-fundamentals-landing-page.ipynb to /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
copying /Users/leahwasser/Documents/github/0-python/test-class/my-course/nbgrader/release/assignment1/2019-09-03-python-fundamentals-landing-page.md to /Users/leahwasser/Documents/github/0-python/test-class/my-course/template_files/ea-assignment1-template
Copied 2 files
Creating 2 extra files
No changes to local repository.
Pushing any changes to remote repository on GitHub
Push to github failed. This is usually because there are changes on the remote that you do not have locally. Here is the github error:
To https://github.com/earth-analytics-edu/ea-assignment1-template
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://95e1990364a22435e5c9b8b449ba6ca5a73f6e4d@github.com/earth-analytics-edu/ea-assignment1-template'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by lwasser** [comment]
@kcranston i think we can merge this PR. my other pr just fixes that gitignore bug and has a few doc updates. should we merge this?

**Pull request merged**
