### PR TITLE
Move cloned student directories into assignment subdirectory 

### PR DESCRIPTION
**Pull request by lwasser**
This addresses #276 . I fixed existing tests but did not add additional ones which is why code cov is unhappy.
 
seems to be working locally after some testing!! and it's a big improvement. NOTE - docstrings throughout need to be fixed up as we work on things. I also found some flake8 issues which i cleaned up on these files only. 

@nkorinek just a note that given you are working on tests today i just went ahead and implemented this as it's getting messy in my subdirectories for our class!!! we may revisit this pr and add docstrings and such! let's chat about that after you finish up with the tests. 

TODO's
- [x] fix black issue (should be easy) - that's why things are failing
- [x] [fix this part of the feedback function](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/feedback.py#L42) to ensure the path includes the directory with the assignment name
```
# Probably should change all calls to `assignment` to `assignment_name` so it's more expressive
repo_name = "{}-{}".format(assignment_name, student)
destination_dir = Path(clone_dir, assignment_name, repo_name)
```
****

i am going to skip tests on this given we are going to restructure the feedback module and tests.
i'll work on some of that in #289 which is also in progress.

### CODE REVIEW

**Comment by kcranston** [comment]
Thanks for tackling this! I think that the feedback tests will also need to be modified for the new path?

**Comment by lwasser** [comment]
oooh you're right @kcranston !! i'm actually not sure how they passed but i will look at them tomorrow.

**Comment by lwasser** [comment]
i was using the tool and it was such an easy change i figured i'd just do it to make life easier locally.

**Comment by lwasser** [comment]
merging this as it's only failing on the codecov. will submit tests in a separate PR!

**Comment by lwasser** [comment]
also noticing we don't have windows testing setup here yet so that will have to be another todo!

**Pull request merged**
