### PR TITLE
Take commit message as script argument

### PR DESCRIPTION
**Pull request by kcranston**
Addresses #466 and #311 

Specifically:
* takes a commit message as a string with the new "commit_message" argument for new_template and update_template
* removes the previous boolean "custom_message" argument
* if commit message not provided, uses "Initial commit" for new_template and "Updating assignment" for update_template

closes #471

### CODE REVIEW

**Comment by lwasser** [comment]
@nkorinek can you please review this?

**Comment by lwasser** [comment]
@nkorinek looking forward to potentially merging this and the other open pr today unless you found bugs?

**Comment by nkorinek** [comment]
Hey! 

Small little bug I ran into I think. The argument `--commit-message` works fine! However, if you run it without that argument I got the following output. 
image

Everything else in this PR seemed to work fine though!

**Comment by nkorinek** [comment]
To tack onto what I mentioned...if a template already exists and you run the argument with `--mode delete` or something like that, you don't get this message. It's only when creating a new template.

**Comment by lwasser** [comment]
oh that's interesting. Isn't it supposed to provide the default message "initial commit" when it's a new template? maybe that somehow broke with this updatE?

**Comment by nkorinek** [comment]
That's what I was thinking, I think the default somehow broke in this pr

**Comment by nkorinek** [comment]
When I run the code that throws the error message on the main branch I don't get the error

**Comment by kcranston** [comment]
Thanks @nkorinek  - let me take a look and see what I broke.

**Comment by kcranston** [comment]
ok, added the default values in argparse so we should never get an empty message now! Current behaviour:

```
(abc-dev) course2022 $  abc-new-template assignment-01 --mode delete
Loading configuration from config.yml
Directory template_repos/assignment-01-template already exists for this course; deleting
                existing files but keeping .git directory, if it
                exists.
No changes to local repository.
Updating assignment list in config
Writing modified config at /Users/karen/Documents/courses-abc/course2022
(abc-dev) course2022  $ abc-new-template assignment-01 --mode delete --commit-message "first commit assigment1"
Loading configuration from config.yml
Directory template_repos/assignment-01-template already exists for this course; deleting
                existing files but keeping .git directory, if it
                exists.
No changes to local repository.
Updating assignment list in config
Writing modified config at /Users/karen/Documents/courses-abc/course2022
(abc-dev) course2022  $ abc-new-template assignment-01 --mode delete --commit-message
usage: abc-new-template [-h] [--commit-message COMMIT_MESSAGE] [--github]
                        [--mode {delete,fail,merge}]
                        assignment
abc-new-template: error: argument --commit-message: expected one argument
```

You get the standard argparse errror when you say you are going to provide a commit message but don't provide one.

**Comment by lwasser** [comment]
fixed a merge conflict! it's rebuilding. we can merge if it passes.

**Pull request merged**
